/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'Seen' : IDL.Null,
  'Approved' : IDL.Null,
  'Rejected' : IDL.Null,
  'UnableToFulfill' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Category = IDL.Variant({
  'Maintenance' : IDL.Null,
  'Stationery' : IDL.Null,
  'ITEquipment' : IDL.Null,
  'Other' : IDL.Null,
  'LabEquipment' : IDL.Null,
});
export const Priority = IDL.Variant({
  'Low' : IDL.Null,
  'High' : IDL.Null,
  'Medium' : IDL.Null,
  'Urgent' : IDL.Null,
});
export const Request = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'completedAt' : IDL.Opt(IDL.Int),
  'title' : IDL.Text,
  'adminActionAt' : IDL.Opt(IDL.Int),
  'submittedByName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'submittedBy' : IDL.Principal,
  'description' : IDL.Text,
  'reviewedAt' : IDL.Opt(IDL.Int),
  'reviewedBy' : IDL.Opt(IDL.Principal),
  'quantity' : IDL.Opt(IDL.Nat),
  'category' : Category,
  'priority' : Priority,
  'reviewRemarks' : IDL.Opt(IDL.Text),
  'expectedDate' : IDL.Text,
  'adminActionNote' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const RequestStats = IDL.Record({
  'total' : IDL.Nat,
  'pending' : IDL.Nat,
  'unableToFulfill' : IDL.Nat,
  'seen' : IDL.Nat,
  'completed' : IDL.Nat,
  'approved' : IDL.Nat,
  'rejected' : IDL.Nat,
});
export const SubmitRequestInput = IDL.Record({
  'title' : IDL.Text,
  'submitterName' : IDL.Text,
  'categoryText' : IDL.Text,
  'priorityText' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Opt(IDL.Nat),
  'expectedDate' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllApprovedRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getAllPendingRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getAllUserProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
  'getRequest' : IDL.Func([IDL.Nat], [Request], ['query']),
  'getStats' : IDL.Func([], [RequestStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markCompleted' : IDL.Func([IDL.Nat], [], []),
  'markSeen' : IDL.Func([IDL.Nat], [], []),
  'markUnableToFulfill' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'rejectRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserProfileForPrincipal' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'submitRequest' : IDL.Func([SubmitRequestInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'Seen' : IDL.Null,
    'Approved' : IDL.Null,
    'Rejected' : IDL.Null,
    'UnableToFulfill' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Category = IDL.Variant({
    'Maintenance' : IDL.Null,
    'Stationery' : IDL.Null,
    'ITEquipment' : IDL.Null,
    'Other' : IDL.Null,
    'LabEquipment' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'Low' : IDL.Null,
    'High' : IDL.Null,
    'Medium' : IDL.Null,
    'Urgent' : IDL.Null,
  });
  const Request = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'completedAt' : IDL.Opt(IDL.Int),
    'title' : IDL.Text,
    'adminActionAt' : IDL.Opt(IDL.Int),
    'submittedByName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'submittedBy' : IDL.Principal,
    'description' : IDL.Text,
    'reviewedAt' : IDL.Opt(IDL.Int),
    'reviewedBy' : IDL.Opt(IDL.Principal),
    'quantity' : IDL.Opt(IDL.Nat),
    'category' : Category,
    'priority' : Priority,
    'reviewRemarks' : IDL.Opt(IDL.Text),
    'expectedDate' : IDL.Text,
    'adminActionNote' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const RequestStats = IDL.Record({
    'total' : IDL.Nat,
    'pending' : IDL.Nat,
    'unableToFulfill' : IDL.Nat,
    'seen' : IDL.Nat,
    'completed' : IDL.Nat,
    'approved' : IDL.Nat,
    'rejected' : IDL.Nat,
  });
  const SubmitRequestInput = IDL.Record({
    'title' : IDL.Text,
    'submitterName' : IDL.Text,
    'categoryText' : IDL.Text,
    'priorityText' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Opt(IDL.Nat),
    'expectedDate' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllApprovedRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getAllPendingRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getAllUserProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyRequests' : IDL.Func([], [IDL.Vec(Request)], ['query']),
    'getRequest' : IDL.Func([IDL.Nat], [Request], ['query']),
    'getStats' : IDL.Func([], [RequestStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markCompleted' : IDL.Func([IDL.Nat], [], []),
    'markSeen' : IDL.Func([IDL.Nat], [], []),
    'markUnableToFulfill' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'rejectRequest' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserProfileForPrincipal' : IDL.Func(
        [IDL.Principal, UserProfile],
        [],
        [],
      ),
    'submitRequest' : IDL.Func([SubmitRequestInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };