/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Maintenance' : null } |
  { 'Stationery' : null } |
  { 'ITEquipment' : null } |
  { 'Other' : null } |
  { 'LabEquipment' : null };
export type Priority = { 'Low' : null } |
  { 'High' : null } |
  { 'Medium' : null } |
  { 'Urgent' : null };
export interface Request {
  'id' : bigint,
  'status' : Status,
  'completedAt' : [] | [bigint],
  'title' : string,
  'adminActionAt' : [] | [bigint],
  'submittedByName' : string,
  'submittedAt' : bigint,
  'submittedBy' : Principal,
  'description' : string,
  'reviewedAt' : [] | [bigint],
  'reviewedBy' : [] | [Principal],
  'quantity' : [] | [bigint],
  'category' : Category,
  'priority' : Priority,
  'reviewRemarks' : [] | [string],
  'expectedDate' : string,
  'adminActionNote' : [] | [string],
  'location' : string,
}
export interface RequestStats {
  'total' : bigint,
  'pending' : bigint,
  'unableToFulfill' : bigint,
  'seen' : bigint,
  'completed' : bigint,
  'approved' : bigint,
  'rejected' : bigint,
}
export type Status = { 'Seen' : null } |
  { 'Approved' : null } |
  { 'Rejected' : null } |
  { 'UnableToFulfill' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export interface SubmitRequestInput {
  'title' : string,
  'submitterName' : string,
  'categoryText' : string,
  'priorityText' : string,
  'description' : string,
  'quantity' : [] | [bigint],
  'expectedDate' : string,
  'location' : string,
}
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveRequest' : ActorMethod<[bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllApprovedRequests' : ActorMethod<[], Array<Request>>,
  'getAllPendingRequests' : ActorMethod<[], Array<Request>>,
  'getAllRequests' : ActorMethod<[], Array<Request>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyRequests' : ActorMethod<[], Array<Request>>,
  'getRequest' : ActorMethod<[bigint], Request>,
  'getStats' : ActorMethod<[], RequestStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markCompleted' : ActorMethod<[bigint], undefined>,
  'markSeen' : ActorMethod<[bigint], undefined>,
  'markUnableToFulfill' : ActorMethod<[bigint, string], undefined>,
  'rejectRequest' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRequest' : ActorMethod<[SubmitRequestInput], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];