/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RequestStats {
    total: bigint;
    pending: bigint;
    unableToFulfill: bigint;
    seen: bigint;
    completed: bigint;
    approved: bigint;
    rejected: bigint;
}
export interface SubmitRequestInput {
    title: string;
    submitterName: string;
    categoryText: string;
    priorityText: string;
    description: string;
    quantity?: bigint;
    expectedDate: string;
    location: string;
}
export interface UserProfile {
    name: string;
    role: string;
}
export interface Request {
    id: bigint;
    status: Status;
    completedAt?: bigint;
    title: string;
    adminActionAt?: bigint;
    submittedByName: string;
    submittedAt: bigint;
    submittedBy: Principal;
    description: string;
    reviewedAt?: bigint;
    reviewedBy?: Principal;
    quantity?: bigint;
    category: Category;
    priority: Priority;
    reviewRemarks?: string;
    expectedDate: string;
    adminActionNote?: string;
    location: string;
}
export enum Category {
    Maintenance = "Maintenance",
    Stationery = "Stationery",
    ITEquipment = "ITEquipment",
    Other = "Other",
    LabEquipment = "LabEquipment"
}
export enum Priority {
    Low = "Low",
    High = "High",
    Medium = "Medium",
    Urgent = "Urgent"
}
export enum Status {
    Seen = "Seen",
    Approved = "Approved",
    Rejected = "Rejected",
    UnableToFulfill = "UnableToFulfill",
    Completed = "Completed",
    Pending = "Pending"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveRequest(requestId: bigint, remarks: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllApprovedRequests(): Promise<Array<Request>>;
    getAllPendingRequests(): Promise<Array<Request>>;
    getAllRequests(): Promise<Array<Request>>;
    getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyRequests(): Promise<Array<Request>>;
    getRequest(requestId: bigint): Promise<Request>;
    getStats(): Promise<RequestStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markCompleted(requestId: bigint): Promise<void>;
    markSeen(requestId: bigint): Promise<void>;
    markUnableToFulfill(requestId: bigint, note: string): Promise<void>;
    rejectRequest(requestId: bigint, remarks: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setUserProfileForPrincipal(user: Principal, profile: UserProfile): Promise<void>;
    submitRequest(input: SubmitRequestInput): Promise<bigint>;
}
import type { Category as _Category, Priority as _Priority, Request as _Request, Status as _Status, SubmitRequestInput as _SubmitRequestInput, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRequest(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllApprovedRequests(): Promise<Array<Request>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllApprovedRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllApprovedRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPendingRequests(): Promise<Array<Request>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPendingRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPendingRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRequests(): Promise<Array<Request>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<[Principal, UserProfile]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyRequests(): Promise<Array<Request>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRequests();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRequests();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRequest(arg0: bigint): Promise<Request> {
        if (this.processError) {
            try {
                const result = await this.actor.getRequest(arg0);
                return from_candid_Request_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRequest(arg0);
            return from_candid_Request_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<RequestStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markCompleted(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markCompleted(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markCompleted(arg0);
            return result;
        }
    }
    async markSeen(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markSeen(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markSeen(arg0);
            return result;
        }
    }
    async markUnableToFulfill(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markUnableToFulfill(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markUnableToFulfill(arg0, arg1);
            return result;
        }
    }
    async rejectRequest(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectRequest(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setUserProfileForPrincipal(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserProfileForPrincipal(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserProfileForPrincipal(arg0, arg1);
            return result;
        }
    }
    async submitRequest(arg0: SubmitRequestInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRequest(to_candid_SubmitRequestInput_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRequest(to_candid_SubmitRequestInput_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Category_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Request_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Request): Request {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    completedAt: [] | [bigint];
    title: string;
    adminActionAt: [] | [bigint];
    submittedByName: string;
    submittedAt: bigint;
    submittedBy: Principal;
    description: string;
    reviewedAt: [] | [bigint];
    reviewedBy: [] | [Principal];
    quantity: [] | [bigint];
    category: _Category;
    priority: _Priority;
    reviewRemarks: [] | [string];
    expectedDate: string;
    adminActionNote: [] | [string];
    location: string;
}): {
    id: bigint;
    status: Status;
    completedAt?: bigint;
    title: string;
    adminActionAt?: bigint;
    submittedByName: string;
    submittedAt: bigint;
    submittedBy: Principal;
    description: string;
    reviewedAt?: bigint;
    reviewedBy?: Principal;
    quantity?: bigint;
    category: Category;
    priority: Priority;
    reviewRemarks?: string;
    expectedDate: string;
    adminActionNote?: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n6(_uploadFile, _downloadFile, value.status),
        completedAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.completedAt)),
        title: value.title,
        adminActionAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.adminActionAt)),
        submittedByName: value.submittedByName,
        submittedAt: value.submittedAt,
        submittedBy: value.submittedBy,
        description: value.description,
        reviewedAt: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.reviewedAt)),
        reviewedBy: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.reviewedBy)),
        quantity: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.quantity)),
        category: from_candid_Category_n11(_uploadFile, _downloadFile, value.category),
        priority: from_candid_Priority_n13(_uploadFile, _downloadFile, value.priority),
        reviewRemarks: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.reviewRemarks)),
        expectedDate: value.expectedDate,
        adminActionNote: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.adminActionNote)),
        location: value.location
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Maintenance: null;
} | {
    Stationery: null;
} | {
    ITEquipment: null;
} | {
    Other: null;
} | {
    LabEquipment: null;
}): Category {
    return "Maintenance" in value ? Category.Maintenance : "Stationery" in value ? Category.Stationery : "ITEquipment" in value ? Category.ITEquipment : "Other" in value ? Category.Other : "LabEquipment" in value ? Category.LabEquipment : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Low: null;
} | {
    High: null;
} | {
    Medium: null;
} | {
    Urgent: null;
}): Priority {
    return "Low" in value ? Priority.Low : "High" in value ? Priority.High : "Medium" in value ? Priority.Medium : "Urgent" in value ? Priority.Urgent : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Seen: null;
} | {
    Approved: null;
} | {
    Rejected: null;
} | {
    UnableToFulfill: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): Status {
    return "Seen" in value ? Status.Seen : "Approved" in value ? Status.Approved : "Rejected" in value ? Status.Rejected : "UnableToFulfill" in value ? Status.UnableToFulfill : "Completed" in value ? Status.Completed : "Pending" in value ? Status.Pending : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Request>): Array<Request> {
    return value.map((x)=>from_candid_Request_n4(_uploadFile, _downloadFile, x));
}
function to_candid_SubmitRequestInput_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitRequestInput): _SubmitRequestInput {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    submitterName: string;
    categoryText: string;
    priorityText: string;
    description: string;
    quantity?: bigint;
    expectedDate: string;
    location: string;
}): {
    title: string;
    submitterName: string;
    categoryText: string;
    priorityText: string;
    description: string;
    quantity: [] | [bigint];
    expectedDate: string;
    location: string;
} {
    return {
        title: value.title,
        submitterName: value.submitterName,
        categoryText: value.categoryText,
        priorityText: value.priorityText,
        description: value.description,
        quantity: value.quantity ? candid_some(value.quantity) : candid_none(),
        expectedDate: value.expectedDate,
        location: value.location
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
